### ISSUE TITLE
"`linuxPackages.nvidia_x11` does not contain `buildInputs`" error when building NVIDIA wrappers.

### ISSUE THREAD

**Issue by 2goodAP** [nix-community/nixGL#173] opened 2024-04-18 11:18 UTC
Non-NVIDIA wrappers build just fine, it's just the NVIDIA wrappers that throw the following error.

![image](https://github.com/nix-community/nixGL/assets/45424904/8bfdd68c-9fcf-48f9-8d50-465a4b74656e)

The problem seems to be in the following section.

![image](https://github.com/nix-community/nixGL/assets/45424904/a5270bf3-1fd1-4a15-be99-590b4a0d003c)

Also, a NixOS module exposes `mkDriver` function for building nvidia drivers. Could we use that here instead of overriding the `nvidia_x11` package?

**Nixpkgs version**: 2b6ee326ad047870526d9a3ae88dfd0197da898d (nixpkgs-unstable)
**Nix version**: 2.13.3
**Host OS**: Ubuntu 24.04 Beta

**Comment by kenranunderscore** [comment] 2024-04-30 05:50
Duplicate of #172?

**Comment by leguteape** [comment] 2024-05-02 08:31
Oops! I seem to have opened the same issue twice. Sorry.

**Closed by leguteape** 2024-05-02 08:31 UTC
